import Navbar from "@/Components/Navbar";
import "./globals.css";
import { Manrope } from "next/font/google";
import Footer from "@/Components/Footer";
import Category from "@/Components/Category";
import About from "@/Components/About";

const menrope = Manrope({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={menrope.className}>
        <Navbar/>
        <div>{children}</div>
        <About />
        <Footer />
      </body>
    </html>
  );
}
